export const mockDirectoryData = [
  {
    id: 1,
    name: "Rajesh",
    type: "lawyer",
    specialization: ["Criminal Law", "Family Law"],
    state: "Delhi",
    city: "New Delhi",
    experience: 12,
    rating: 4.8,
    casesHandled: 245,
    email: "rajesh987@example.com",
    phone: "+91-9812345678",
    verified: true,
    available: true,
    languages: ["English", "Hindi", "Punjabi"],
    qualification: "LLB, Delhi University",
    mission: "Dedicated to providing justice in family and criminal matters",
    
    
  },
  {
    id: 2,
    name: "Legal Aid Society",
    type: "ngo",
    specialization: ["Human Rights", "Consumer Protection"],
    state: "Maharashtra",
    city: "Mumbai",
    experience: 8,
    rating: 4.6,
    casesHandled: 523,
    email: "contact@legalaid.org",
    phone: "+91-9876543210",
    verified: true,
    available: true,
    languages: ["English", "Hindi", "Marathi"],
    mission: "Ensuring access to justice for marginalized communities",
    qualification: "LLB, Delhi University"
  },
  {
    id: 3,
    name: "Nair",
    type: "lawyer",
    specialization: ["Property Law", "Civil Law"],
    state: "Karnataka",
    city: "Bangalore",
    experience: 6,
    rating: 4.7,
    casesHandled: 189,
    email: "nair0007@example.com",
    phone: "+91-9123456789",
    verified: true,
    available: false,
    languages: [
      "English","Hindi","Bengali","Telugu","Marathi","Tamil","Urdu",
      "Gujarati","Kannada","Malayalam","Punjabi","Other"
    ],
    qualification: "LLM, National Law School of India",
    mission: "Specializing in property disputes and civil litigation",
   
    
  },
  {
    id: 4,
    name: "Justice for Engineers",
    type: "ngo",
    specialization: ["Corporate Law", "Public Interest Litigation"],
    state: "Uttar Pradesh",
    city: "Lucknow",
    experience: 15,
    rating: 4.9,
    casesHandled: 892,
    email: "info@justiceforengg.org",
    phone: "+91-9988776655",
    verified: true,
    available: true,
    languages: ["English", "Hindi"],
    qualification: "Accredited NGO providing legal aid",
    mission: "Empowering engineers through legal aid and policy reform",
   
    
  },
  {
    id: 5,
    name: "A.K Singh",
    type: "lawyer",
    specialization: ["Corporate Law", "Tax Law"],
    state: "Gujarat",
    city: "Ahmedabad",
    experience: 10,
    rating: 2.5,
    casesHandled: 167,
    email: "ak.singh@example.com",
    phone: "+91-9765432109",
    verified: true,
    available: true,
    languages: ["English", "Hindi", "Gujarati"],
    qualification: "LLB, Gujarat National Law University",
    mission: "Focused on corporate compliance and tax advisory",
    
    
  },
];